src/app/core/rpc/rpc.service.ts

Prevent accidental recursive loops by calling this._rpc.poll()

Make polling (start/stop) private

---

src/app/core/status/status.component.html

This is fix for visual glitch when user moves pointer over status icon tooltip get shown and than start flickering and reposition itself.
Fixed by attaching tooltip to documents body instead of parent container.

Fix for status icon tooltip flickering

---

src/app/core/rpc/blockstatus.service.ts
src/app/modals/syncing/syncing.component.html
src/app/modals/syncing/syncing.component.ts

PAR-151
Can't test this : if the daemon is already running when internet is disconnected, peersList still contains the peers that were connected before. If starting the daemon after internet is disconnected, RPC service doesn't emit updates.

error message in syncing modal if RPC connected but no peers

---

src/app/app.component.ts
src/app/modals/modals.component.spec.ts
src/app/modals/modals.service.ts

- added an array of `manuallyClosed` modal names (e.g. `SyncingComponent`) to the Modals service
- modal name is pushed to the array when the modal is first closed
- add `{forceOpen: true}` to force open a modal that may have been closed, e.g. when manually opening with a button press

fixed modals poping when manually closed

---

modules/clientBinaries/clientBinaries.js

This commit disables auto-updating every hour on the daemon, thus disabling the automatic restart of the wallet. Wallet core daemon will still update on launch.

Disabling auto-update

---

modules/clientBinaries/clientBinaries.json
modules/daemon/daemonManager.js

This PR will bump all clients built from **develop** to 0.15.1.0 so we can test it before release.
Wallets from the official builds will **not** bump.
I will need to do more work to automatize this behaviour before next GUI release, if i'm not done with it we can simply change it manually by pasting the commented link to master.
Please rebase `develop` if you're currently working on a feature to bump core.

bumping core to 0.15.1.0 for develop

---

src/app/modals/syncing/syncing.component.html

- fixes https://github.com/particl/partgui/issues/314
- removes unused `ngIf="!syncPercentage` part of the syncing modal, which was broken and never showed for more than a fraction of a second

removed unused sync modal part

---

src/app/modals/shared/percentage-bar/percentage-bar.component.html
src/app/modals/shared/percentage-bar/percentage-bar.component.scss
src/app/modals/syncing/syncing.component.html
src/assets/theme.scss

When launched and blockchain isn't synced, the syncing modal (see #356) still fires up, even though it's empty.
We need not to launch the modal at all, syncing process is shown in the sidebar menu now.
(develop branch)
issue: https://github.com/particl/partgui/issues/381

Sync modal

---

src/app/wallet/shared/transaction-table/transaction-table.component.html
src/app/wallet/shared/transaction-table/transaction-table.component.scss
src/app/wallet/shared/transaction.model.ts

- added status icons notifying about included narration
- narration content displayed in TX detail
- fixes https://github.com/particl/partgui/issues/350
- **still needs implementation of displaying narration content etc.** (I've just prepared the styling)
Preview:

Narration implementation

---

src/app/wallet/wallet/shared/transaction-table/transaction-table.component.html
src/app/wallet/wallet/shared/transaction.model.ts

Narrations were already done and working, merged to develop (#357). Now on dev (and even on restructure), the narrations aren't working anymore.
I've checked if the changes from #357 are included and yes, they are there. Probably some logic changed during restructure and that might broke it.
So we need the narrations to display again.

Display narration text

---

src/app/wallet/wallet/shared/address-table/address-table.component.ts

Resolve : 
>In Address book, selecting more items per page is not working. Always stays at 5 displayed items per page, even if you select 20.

Resolve Address book - paginator bug #529

---

src/app/modals/encryptwallet/encryptwallet.component.html
src/app/modals/modals.component.html
src/app/modals/shared/password/password.component.scss
src/app/modals/shared/password/password.component.ts
src/assets/theme.scss

Closes https://github.com/particl/partgui/issues/546
- fixes misplaced icons (for some reason the buttons there don't have `.mat-button` class, so they weren't getting the styles)
- fixed focused modal's close button on open (that's why the grey background was there)

Create wallet modal (GFX fix)

---

src/assets/theme.scss

Probably due to Material's update, the sidebar's menu layout got damaged a bit. This is a fix for that.

fix sidebar's menu layout

---

src/app/core-ui/main/main-view.component.html
src/app/core-ui/main/main-view.component.scss
src/app/core-ui/main/main-view.module.ts
src/app/core-ui/main/release-notification/release-notification.component.html
src/app/core-ui/main/release-notification/release-notification.component.scss
src/app/core-ui/main/release-notification/release-notification.component.spec.ts
src/app/core-ui/main/release-notification/release-notification.component.ts
src/app/core-ui/main/release-notification/release-notification.model.ts

- added notification bar (closes https://github.com/particl/partgui/issues/488, https://github.com/particl/partgui/issues/489)
- green one for infos, updates etc.
- red one for more important stuff

Info/warning for GUI updates

---

src/app/modals/coldstake/coldstake.component.ts
src/app/modals/shared/password/password.component.ts
src/app/modals/unlockwallet/unlockwallet.component.html
src/app/modals/unlockwallet/unlockwallet.component.ts
src/app/wallet/overview/widgets/coldstake/coldstake.component.html
src/app/wallet/overview/widgets/coldstake/coldstake.component.ts

cold staking widget state different scenarios fixing

---

src/app/wallet/wallet/address-book/address-book.component.html
src/app/wallet/wallet/address-book/address-book.component.scss
src/app/wallet/wallet/addresslookup/addresslookup.component.html
src/app/wallet/wallet/addresslookup/addresslookup.component.scss
src/app/wallet/wallet/history/history.component.html
src/app/wallet/wallet/receive/receive.component.html

Add All search
Input with a clear button #610 
>> Right now all search input doesn't have a clear button, we need to clear that input by backspace. so I hope we should add clear button.
here is a preview of a clear button :

Input clear button

---

src/app/wallet/wallet/address-book/modal/new-address-modal/new-address-modal.component.html
src/app/wallet/wallet/addresslookup/addresslookup.component.scss
src/app/wallet/wallet/history/history.component.html
src/app/wallet/wallet/history/history.component.scss
src/app/wallet/wallet/receive/modals/add-address-label/add-address-label.component.html
src/app/wallet/wallet/send/send.component.html
src/app/wallet/wallet/shared/signature-address-modal/signature-address-modal.component.html
src/app/wallet/wallet/shared/signature-address-modal/signature-address-modal.component.scss
src/app/wallet/wallet/shared/transaction-table/transaction-table.component.html
src/app/wallet/wallet/shared/transaction-table/transaction-table.component.scss
src/assets/_config.scss
src/assets/theme.scss

Mainly small GFX fixes and tweaks & solution to Henk's layout issue:
- focus inputs when modals are opened
- fixed layout on Address lookup & Verify/sign modals
- hopefully fixed modals' content misalignment issues
- disabled missing text selection on few places

modal fixes & fixed consistency of icons

---

src/app/wallet/wallet/shared/transaction.service.ts

slow block confirmation updated fix

---

src/app/wallet/shared/util/utils.ts
src/app/wallet/wallet/address-book/address-book.component.html
src/app/wallet/wallet/address-book/address-book.component.scss
src/app/wallet/wallet/address-book/address-book.component.ts
src/app/wallet/wallet/shared/address-table/address-table.component.ts

*added the ability to filter address book by using filters
*updated reg expressions in addressHelper utility

added filter options on addressBook

---

src/app/wallet/wallet/shared/transaction.model.ts

after zapping and cancel zap, I see history list and overview page having an error, Transaction modal having some issue.  because zap balance transfer does not return output (address etc.. )

Small changes for zap(blance transfer) tx record

---

src/app/core/rpc/rpc-state/rpc-state.class.ts

wallet checking was broken as it checked for wallet creation by sending the `extkey list` RPC command which has non deterministic result (if gui crashed during wallet creation for instance)
Replacing by correct logic using `walletsettings` and checking if `hdmasterkey` is set.

updating wallet checking logic

---

src/app/core-ui/main/status/status.component.html
src/app/core-ui/main/status/status.component.ts
src/assets/icons/SVG/lock/lock-off.svg
src/assets/icons/SVG/lock/lock-stake.svg
src/assets/icons/SVG/lock/lock.svg
src/assets/icons/SVG/network/peers-0.svg
src/assets/icons/SVG/network/peers-1.svg
src/assets/icons/SVG/network/peers-2.svg
src/assets/icons/SVG/network/peers-3.svg
src/assets/icons/SVG/network/peers-4.svg
src/assets/icons/SVG/network/peers-5.svg
src/assets/icons/SVG/network/peers-6.svg

Fixes #680 
- switched status icons to SVG
- took the opportunity to switch color of locked and unlocked wallet (IMO red as locked and green as unlocked is perceived more logically) – I can ofc switch that back if you don't share my views

Status icons (retina) fix

---

src/app/core-ui/main/release-notification/release-notification.component.ts

For checking new update API calls every time on git repository after changing git repo URL it will not work so that should be updated if repository updated.

Update Git Release URL #735

---

src/app/wallet/wallet/addresslookup/addresslookup.component.ts
src/app/wallet/wallet/shared/signature-address-modal/signature-address-modal.component.html
src/app/wallet/wallet/shared/signature-address-modal/signature-address-modal.component.ts

In Sign Verify Modal
- **Sign Message**: Address lookup modal display private address not public and I guess we need to display public address in sign message > address lookup, so addresses lookup modal should be refactored. Also after signed address user got a signature key, There is no copy options, so I've added it. 
- **Verify Message**: Its work fine, addresse lookup show only address book address which user need to verify etc. Only here I added paste button for paste signature. 
https://github.com/particl/particl-desktop/issues/734

Sign/Verify modal Refactoring 

---

src/app/core-ui/main/main-view.component.ts

This commit adds an `event.preventDefault()` to avoid double pasting in os x, described in issue #817

fix osx double pasting

---

src/app/wallet/wallet/shared/qr-code-modal/qr-code-modal.component.html
src/assets/theme.scss
src/styles.scss

Address Book QR not shown #835
Testing 1.1.0 RC 5 release.
Address Boot Tab, when trying to view the Address QR code using the "Show QR Code" button, only the address is available. No QR code are shown.

Adds new angularx-qrcode in qr-code-modal

---

modules/options.js
src/app/_test/wallet-test/send-test/send-mock.service.ts
src/app/core/state/state.service.ts
src/app/core/util/utils.ts
src/app/wallet/wallet/send/send-confirmation-modal/send-confirmation-modal.component.html
src/app/wallet/wallet/send/send-confirmation-modal/send-confirmation-modal.component.scss
src/app/wallet/wallet/send/send-confirmation-modal/send-confirmation-modal.component.spec.ts
src/app/wallet/wallet/send/send-confirmation-modal/send-confirmation-modal.component.ts
src/app/wallet/wallet/send/send.component.html
src/app/wallet/wallet/send/send.component.spec.ts
src/app/wallet/wallet/send/send.component.ts
src/app/wallet/wallet/send/send.service.ts
src/app/wallet/wallet/send/transaction-builder.model.ts

- fixes #637 
- more previews for [blind TX](https://i.imgur.com/U1wEqBH.png) & [anon TX](https://i.imgur.com/Z1at8Hb.png)
- so far only static (= not working) layout → needs to be connected to the backend
- redesigned layout of TX confirmation modal
- added TX information (info about public/blind/anon TXs and their implications)
- added fee estimations
- added fiat countervalues (when ready to be implemented)
Note: this PR was based on @pciavald's https://github.com/particl/particl-desktop/pull/724 because I couldn't access the Send tab due to the bug on `dev`. If needed, I can rebase on `dev` when fixed.

TX confirmation modal 2.0

---

src/app/market/buy/checkout-process/checkout-process.component.ts

Just quickfix for JS exception, probably it would be better to find out why `this.selectedAddress` is not defined on view destruction.

Hotfix for #952: sidebar tabs wont work anymore after clicking "Buy"

---

src/app/core/market/api/bid/bid.service.ts
src/app/market/buy/checkout-process/checkout-process.component.ts

GUI error handling for "No unspent outputs" and "Insufficient funds"
If this is returned:
2018-05-22T09:17:08.315Z - warn: [api\services\BidActionService] You are too broke...
2018-05-22T09:17:08.318Z - info: [app] POST /api/rpc 404 129.336 ms - 81
Message should display as follow:
Insufficient funds to place the order.
And for this error:
2018-05-22T09:28:50.170Z - warn: [api\services\BidActionService] No unspent outputs
2018-05-22T09:28:50.173Z - info: [app] POST /api/rpc 404 87.016 ms - 77
Please display:
No unspent outputs available. Please complete active locked escrow.

error handling while bidding on order according to scenarios

---

src/app/core/market/market-cache/add-to-cart-cache.service.ts

- Updated search cmd to fix error "page number should be number".
As now `bid search` cmd already updated everywhere except here.

Update bid search cmd param
